### ISSUE TITLE
Version 3 - Quitting Crashes 3DS.

### ISSUE THREAD

**Issue by CodingKoopa** [tommai78101/homebrew#1]
When starting a 3DSX compiled from [version 3](https://github.com/tommai78101/homebrew/wiki/Version-3:-Basic-3D-Rendering) of the wiki, text will [start to fade away](http://i.imgur.com/NYp0B2f.jpg) and then everything will freeze without a Luma crash dump.

A9LH Old 3DS 11.0.0-33U Luma, Homebrew Launcher ran via CIA.

**Comment by tommai78101** [comment]
I can confirm it crashes, but I have no idea if I should just close this issue just because it's no longer supported (we're on Version 8 as of July 18, 2016), and there are no crashes in Version 8 that Version 3 has.

As for "text starting to fade away", how did you have that?

**Comment by CodingKoopa** [comment]
The text does not fade away when it is running, that only happens after pressing start.

**Comment by tommai78101** [comment]
Are you okay with me closing this issue? I don't plan to fix old code.

**Comment by CodingKoopa** [comment]
Sure.
