### ISSUE TITLE
C with/or C++

### ISSUE THREAD

**Issue by YugamiSekai** [tommai78101/homebrew#2]
People still use C with 3DS homebrew so I was wondering if you could possibly use C instead or with C++ since that would easier.

**Comment by tommai78101** [comment]
I am currently using C++.

**Comment by CodingKoopa** [comment]
A decent amount of the concepts used by Citro3D in C++ are still applicable to C, I think that this is fine.

**Comment by tommai78101** [comment]
I thought @kprovost7314 is asking if the project will become C or C++. Right now, I am moving over to Function Overloading, Smart Pointers, with Entity Component System and Polymorphism/Inheritance already set in stone.

**Comment by tommai78101** [comment]
I'm going to link your thread here for future references. I believed this is a good starting point for all of us in moving forward with this issue.

[Citro3D C language tutorial](https://gbatemp.net/threads/the-un-official-3ds-homebrew-development-guide.430034/), by @kprovost7314.

Closing this issue, as it has now been resolved by the link above.
